trigger:
  paths:
    include:
    - doc
    - README.md
    - CHANGES.md
    - CONTRIBUTING.md

pr:
  paths:
    include:
    - doc
    - README.md
    - CHANGES.md
    - CONTRIBUTING.md

resources:
  pipelines:
  - pipeline: main-build
    source: main-build-CI
    trigger:    
      stages:
      - build_gcc

stages:
  - stage: documentation
    displayName: Documentation
    jobs:
      - job: documentation
        displayName: Generate Documentation
        pool:
          vmImage: 'Ubuntu 20.04'
        variables:
          BUILD_DIR: '$(Agent.BuildDirectory)/build'
          DOC_DIR: '$(Agent.BuildDirectory)/documentation'
          CHANGELOG: '$(Agent.TempDirectory)/changelog'
        steps:
          - script: echo Documentation pipeline successfully run!
  - stage: tutorials
    displayName: Tutorials
    condition: eq(variables['Build.Reason'], 'ResourceTrigger')
    jobs:
      - job: tutorials
        pool:
          vmImage: 'Ubuntu 20.04'
        steps:
          - script: echo triggered by build_gcc after it completed successfully!
